### ISSUE TITLE
Can't make it work for other bars.

### ISSUE THREAD

**Issue by aeerdogan** [tflo/Action-Bar-Button-Growth-Direction#2]
Hello. Addon works for bar 1. I followed the instructions for the lua file. 
1. I tried y = "all", did not work.
2. I tried y = "some" and setting it "true" for individual bars. Still no success.

I'm attaching my final lua for step 2 and a screenshot. Thanks for your work.
[main.zip](https://github.com/user-attachments/files/18134465/main.zip)
![bar_growth](https://github.com/user-attachments/assets/a89727ff-1a3a-4526-a776-d7b1aa98bcc0)

**Comment by tflo** [comment]
The file you have uploaded (main.lua) is the addon code, you should not modify that.

What you have to modify is the _ActionBarButtonGrowthDirection.lua_ in your SavedVariables folder. Please check out the [Setup section](https://github.com/tflo/Action-Bar-Button-Growth-Direction?tab=readme-ov-file#setup) of the ReadMe (or the description on CurseForge, which is the same). It explains where you find the file and how to activate the mod for other bars.

The table in the SavedVariables file looks similar to the defaults table you have found in the addon code. You have to be logged out when editing and saving the file (no need to quit WoW, but your char must be logged out).

In short:

Your step 2 is correct, so, if you want to reverse the Y-axis for bars 1 to 3, it should look like this:

```lua

ABBGD_db = {
["y"] = {
true,
true,
true,
false,
false,
false,
false,
false,
},
["x"] = {
false,
false,
false,
false,
false,
false,
false,
false,
},
["method"] = 1,
["db_version"] = 1,
["enable"] = {
["y"] = "some",
["x"] = "none",
},
}
```

Please note that the _order_ of the keys can be different in your SavedVariables file (e.g. the ["x”] section can be before the ["y"] section), so doublecheck if you are editing for the correct axis.

I would not do step 1, because with that you reverse the respective axis of all bars.

Personally I play with the reversed Y-axis of action bar 1 without any issues since I created the addon (1½ years). But I have never tested the other bars over a long period of time. Probably it will work equally fine, but who knows…

**Comment by aeerdogan** [comment]
Thank you, this is what happens when you don't read instructions carefully :).

**Comment by tflo** [comment]
Seems it works now for you, closing this.
